from . import backend_configurator
from . import bookmark
from . import facilsoft_app_group
from . import favorite_apps
from . import global_search
from . import google_font_family
from . import ir_http
from . import ir_menu
from . import ir_module
from . import mail_channel
from . import mail_firebase
from . import multi_tab
from . import push_notification_menu
from . import pwa_shortcuts
from . import res_company
from . import res_config_setting
from . import res_users
from . import to_do_list
